# Generated by Django 5.2.4 on 2025-07-24 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deudor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.TextField()),
                ('tipo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('contraseña', models.CharField(max_length=128)),
                ('rol', models.IntegerField(choices=[(1, 'Administrador'), (2, 'Cobrador')])),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField()),
                ('saldo_pendiente', models.IntegerField()),
                ('interes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('meses', models.IntegerField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('estado', models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Pagado'), (3, 'Vencido')], default=1)),
                ('deudor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.deudor')),
                ('cobrador', models.ForeignKey(limit_choices_to={'rol': 2}, on_delete=django.db.models.deletion.CASCADE, to='gestion.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_pagado', models.IntegerField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='gestion.prestamo')),
            ],
        ),
    ]
