# Generated by Django 5.2.4 on 2025-07-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_prestamo_monto_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='monto_total',
        ),
        migrations.AlterField(
            model_name='deudor',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='deudor',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Normal'), (2, 'Especial')], default=1),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='interes',
            field=models.IntegerField(choices=[(10, '10%'), (15, '15%'), (20, '20%')], default=0),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='meses',
            field=models.IntegerField(choices=[(1, '1 mes'), (2, '2 meses')], default=1),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='saldo_pendiente',
            field=models.IntegerField(blank=True),
        ),
    ]
